### ISSUE TITLE
there is no way to mock-out a primitive

### ISSUE THREAD

**Issue by lbartnik** [n-s-f/mockery#9] opened 2016-11-09 18:35 UTC
Neither `with_mock` nor `stub` will let you mock-out R's `primitive`. Check out this package and sample tests there: https://github.com/lbartnik/mockExample

**Comment by lbartnik** [comment] 2016-11-09 20:13
here's an example of how to unlock an environment
https://gist.github.com/wch/3280369#file-unlockenvironment-r

**Comment by lbartnik** [comment] 2016-11-09 20:42
one should:

- find the function under test - we want to intercept calls originating from this function; name it X
- unlock environment which function X belongs to
- add a new entry in this unlocked environment named after the primitive we want to mock
- lock the environment

it can be done in pure R as well but requires additional environment:

- take a copy of function X
- put this copy in a new environment whose parent is the env of X
- add the intercept for the primitive in the new env
- unlock binding for original X in its env
- replace X with its copy
- lock binding

the second method is more complex and makes it a bit more difficult to replace the same primitive in subsequent calls or to replace multiple primitives

**Comment by n-s-f** [comment] 2016-11-09 21:26
@lbartnik 

Stub actually already works with this! Look at the error message from the test in your example from the stub test:

```
'mesages' does not match "Hello, World!".
Actual value: "Hello, world!\n"
```

The only difference is the newline. `with_mock` actually does not work - it seems to think `interactive` is not a function.

**Comment by n-s-f** [comment] 2016-11-09 21:28
I also ran this little experiment in an interactive session:

```.R
> f = function() {
    if (interactive()) {
       return('interactive')
    } 
    return('not interactive')
}
> f()
[1] "interactive"
> library(mockery)
> stub(f, 'interactive', FALSE)
> f()
[1] "not interactive"
```

**Comment by n-s-f** [comment] 2016-11-09 21:30
@lbartnik 

It makes sense that this should work - we're actually just sticking a thing with the name `interactive` into the env in which the function is executing. When the function goes to call `interactive`, it immediately finds that thing before it even gets to find the primative. The fact that the name is shadowing a primative shouldn't matter at all.

**Comment by n-s-f** [comment] 2016-11-09 21:37
@lbartnik IActually I was wrong - the issue is not the newline. It turns out `expect_message` knows how to ignore the newline generated in the message.

The issue is that you've capitalized "World" is the test, but not in the actual code. If you fix that, then the `stub` test passes.

**Comment by lbartnik** [comment] 2016-11-09 21:38
Do you run it via Ctrl+T?

**Comment by lbartnik** [comment] 2016-11-09 21:39
Make sure you run this test in a non-interactive R session

**Comment by n-s-f** [comment] 2016-11-09 21:45
@lbartnik Yes, I still get that the test passes when I'm not running it in a interactive R session, once I've made the modification to the spelling.

I don't run via Ctrl + T - that doesn't work on my system. What error message do you get for the stub test when it fails?

**Comment by lbartnik** [comment] 2016-11-09 21:52
OK, you're right. I thought expect_* evaluated the call in an environment where the function wasn't changed. I need to look at the original code, maybe my example doesn't follow it close enough.

Also, if you want to replace that call for another function, let's say hello() calls world() and only in world() you check for the primitive, but test code calls hello() - in that case I believe world() will not see the stubbed primitive but call the original one.

**Comment by n-s-f** [comment] 2016-11-09 21:52
@lbartnik 

Correct, the stubbing does not trickle down to lower function calls.

This is by design, though. I don't think it's good testing practice to stub something out several layers down. I think either the function 1 layer should be stubbed (in the case, `world`) rather than the function that function calls. If you want to test the `world` function, there can be a different test function that calls `world` directly.

That said - if `world` is in the scope of the test, there's technically nothing stopping you from stubbing in the env of world in the test, and the calling `hello`. But that seems like very dangerous territory.

**Comment by n-s-f** [comment] 2016-11-09 22:05
@lbartnik I'll close this issue, because stubbing primatives is possible. If you want to raise the possibility of changing the scope of the stubbing function, let's discuss offline or in a new issue.

**Closed by n-s-f** 2016-11-09 22:05 UTC
