### ISSUE TITLE
R6 methods, and functions called by R6 methods

### ISSUE THREAD

**Issue by gaborcsardi** [n-s-f/mockery#13] opened 2016-11-23 13:12 UTC
Stubbing does not seem to work for them. I'll add a reproducible example later, my current one is rather big....

**Comment by gaborcsardi** [comment] 2016-11-23 15:06
OK, I realize that this will never work, because you assign back the function to the calling environment, and the R6 method will be called from a different environment. 

It is a pity, though.

**Comment by n-s-f** [comment] 2016-11-23 18:02
@gaborcsardi Thanks for filing this bug report!

I'd still be interested in looking into this. 

Consider this: we assign the function that points to the mock function to the environment that the R6 method is called from, but we add some code to that function so that when it's done executing once (or a user-chosen number of times) it removes itself from the calling environment and reinstates the original function.

**Comment by gaborcsardi** [comment] 2016-11-24 09:31
I think this is error prone, because if an error happens (e.g. a test case fails), the mock function will not be called the requested number of times (or at all).

It is also different from what you have now, so it would be confusing.

**Comment by n-s-f** [comment] 2016-11-24 13:34
I agree on both counts. I wouldn't put this in unless I can find a way around the first issue, and I believe the confusion can be minimized in the code. The interface to the user shouldn't change at all, modulo perhaps an optional parameter to `stub`.

**Comment by n-s-f** [comment] 2016-11-25 13:49
@gaborcsardi 

So there are actually a few reasonable-ish ways of dealing with this.

To mock out calls to R6 methods from other functions, we can mock out the `$` primative in the calling function so that the call to the R6 method is mangled into something that can be easily mocked (and all other usages of `$` remain unchanged). This is very similar to what we do with `::`, and can be done reliably.

To mock out calls to functions from within R6 methods, we note the following. R6 objects are actuallly just environments, and R6 methods are just closures. I think it's reasonable to think that it's okay to mock things out of closures _without_ having those mocks disappear at the end of the test. This is how most mocking libraries in other languages work - we can leave it up to the user to provide fresh instances of each object for each test, which is good practice anyway so state (like this) doesn't get messed up. Alternatively, we can mock out `$` _in the test function_, in which case the mocks wouldn't carry over between tests, even if the same exact object is used.

I'll start working on this soon.

**Comment by n-s-f** [comment] 2016-11-25 14:03
Here are the test cases I'll be working from https://github.com/n-s-f/mockery/blob/380d81e1439969908a767e484939450b17b1b9ad/tests/testthat/test_stub.R#L197-L230

Let me know if your use-case is not covered by those.

**Comment by gaborcsardi** [comment] 2016-11-25 14:06
Thanks! My use case is this I believe:
https://github.com/n-s-f/mockery/blob/380d81e1439969908a767e484939450b17b1b9ad/tests/testthat/test_stub.R#L207-L212

So it is covered.

**Comment by n-s-f** [comment] 2016-11-26 13:58
Great, so all tests are passing in this branch: https://github.com/n-s-f/mockery/tree/r6-stubbing-nsf

However I still want to clean up the code (I introduced some duplication) and add some more tests around the edge cases, so I'll probably merge this next weekend.

Incidentally, I found some very strange behavior in R such that unless [this line](https://github.com/n-s-f/mockery/blob/r6-stubbing-nsf/R/stub.R#L105), which shouldn't do anything, is there, the closure seems to break, in the sense that all the closure created by that function take the value of the last parameter passed to the closure generating function! I may look into this more before merging as well.

**Comment by gaborcsardi** [comment] 2016-11-26 14:46
Cool. I'll test it later today.

As for the mysterious line, it is because of the lazy evaluation of
function arguments.

**Comment by n-s-f** [comment] 2016-12-03 12:48
@gaborcsardi Did you have any issues with this? I'm planning on merging later today.

Thanks.

**Comment by gaborcsardi** [comment] 2016-12-03 13:16
Haven't tried yet, sorry. I'll try later today.

**Comment by n-s-f** [comment] 2016-12-03 14:11
No problem, thanks. I just found a minor bug I'm working through as well, so no rush.

**Comment by n-s-f** [comment] 2016-12-03 14:37
That bug is gone. If you have a chance to test it for your use case today, merge the code after that. Otherwise I'll merge it at the end of the day.

Thanks again for letting me know about the missing feature!

**Comment by gaborcsardi** [comment] 2016-12-03 22:59
So, how do you actually restore the original state?

**Comment by n-s-f** [comment] 2016-12-04 02:23
The path I went with is that I don't change the state. Instead I stub the `$` operator out in the env of the test to mangle the name before evaluating the function call, and I insert a function with the mangled name (with the appropriate function mocked out) back into the test env.

**Comment by n-s-f** [comment] 2016-12-04 02:24
I'm going to merge the code above. If it solves your use case, please close the issue. Otherwise please elaborate further.

Thanks!

**Comment by frbl** [comment] 2017-07-04 17:35
Sorry to reopen this issue, but I had some issues getting this to work on my own code. I've created a MWE in https://github.com/n-s-f/mockery/pull/18. 

The thing is that the mocking works fine whenever you're not calling other objects from within the code. If you do call other objects, for some reason it can't find them (hence the failing specs). Note the print statement in the spec in the PR. Its output is:

```
DONE ===========================================================================
Rerunning tests:  test_stub.R
stub: .................................<some_class>
  Public:
    clone: function (deep = FALSE)
    external_method: function ()
1...........

Failed -------------------------------------------------------------------------
1. Error: stub works with R6 methods that have other objects in them (@test_stub.R#226)
object 'other' not found
1: expect_equal(obj$method_with_other(), "stub has been called") at mockery/tests/testthat/test_stub.R:226
2: compare(object, expected, ...)
3: obj$method_with_other()
4: other$external_method at mockery/tests/testthat/test_stub.R:203
5: eval(parse(text = code), eval_env) at mockery/R/stub.R:110
6: eval(parse(text = code), eval_env)
```
As you can see it can actually print the object, but calling it right thereafter raises an error.

Any ideas?

**Comment by n-s-f** [comment] 2017-07-04 22:04
Thanks for opening the issue. I think this is solved by the code I developed for https://github.com/n-s-f/mockery/issues/17. If I recall, that code just needed a little bit of cleaning up. If you're up for looking through it, you can see if that solves your problem. Otherwise I'll take a closer look this weekend.

**Comment by n-s-f** [comment] 2017-07-05 14:11
This is a different problem than I thought. I will fix it in your pull request.

**Comment by n-s-f** [comment] 2017-07-05 14:16
@frbl This is fixed in https://github.com/n-s-f/mockery/pull/18.  Please verify that this resolved the problem. If so, please close this issue.

Thanks!

**Comment by n-s-f** [comment] 2017-07-05 18:40
I'm sorry - I was wrong about this again. The issue is that everything that uses `$` or `::` gets evaluated in the functions calling environment, where `object` doesn't exist. This is tricky because it's hard to gain access to the execution environment. I'll revert that pull request and think about this more over the weekend. Let me know if you have any ideas.

**Comment by n-s-f** [comment] 2017-07-05 20:11
Happy to report this is fixed on master. The relevant commit is https://github.com/n-s-f/mockery/commit/563b24f5886832602ab469c3e647d60d5082c234.

**Comment by frbl** [comment] 2017-07-06 10:48
Hi @n-s-f, 

Thanks a lot for the super fast response. I will test it out as soon as possible, which is probably tomorrow, and I'll report back.

Thanks,
Frank

**Comment by n-s-f** [comment] 2017-07-06 12:19
Sounds good, thanks!

**Comment by n-s-f** [comment] 2017-07-21 13:11
@frbl Have you had a chance to see if this solves you problem? I think the tests I included are the same as the specs that failed in your example, but I'm curious if there are further issues.

**Comment by frbl** [comment] 2017-07-25 19:15
Hi @n-s-f, sorry for the super late response. I've finally tried it,   but it does not seem to work. However, it doesn't crash either (which it did do before). I'll try some different things now and see if I can find out what's wrong.

**Comment by n-s-f** [comment] 2017-07-25 19:29
@frbl Thanks for testing.

Would you mind adding some failing specs that demonstrate the issue?

I've just pushed a commit (https://github.com/n-s-f/mockery/commit/db24bc0b8bd80e4ff15c442b272ce2b9bb541d6f) that adds back the exact specs that you added in originally. 

I can run these with no failures on master, so there must be some additional issue not covered by these specs.

Thanks.

**Comment by frbl** [comment] 2017-07-25 19:30
No there was something wrong in my code, and I fixed it. I removed my old comment, so never mind. It works :-)

**Comment by n-s-f** [comment] 2017-07-25 19:32
@frbl Great! Thanks for opening the issue.

**Closed by n-s-f** 2017-07-25 19:32 UTC
